### ISSUE TITLE
No n_* Object Statistics? 

### ISSUE THREAD

**Issue by derekmpage** [finalsite/varnish-mib#1]
I am just curious why n_* object statistics were not included in the MIB.

For example.

Most important (must have) n_ statistics:

MAIN.n_object
MAIN.n_expired
MAIN.n_lru_nuked
MAIN.n_purges 

Here are all the n_ statistics. 

MAIN.n_object                   521          .   object structs made
MAIN.n_vampireobject              0          .   unresurrected objects
MAIN.n_objectcore               640          .   objectcore structs made
MAIN.n_objecthead               696          .   objecthead structs made
MAIN.n_waitinglist              198          .   waitinglist structs made
MAIN.n_backend                    1          .   Number of backends
MAIN.n_expired               808147          .   Number of expired objects
MAIN.n_lru_nuked                  0          .   Number of LRU nuked objects
MAIN.n_lru_moved               7959          .   Number of LRU moved objects
MAIN.n_vcl                        1         0.00 Number of loaded VCLs in total
MAIN.n_vcl_avail                  1         0.00 Number of VCLs available
MAIN.n_vcl_discard                0         0.00 Number of discarded VCLs
MAIN.n_purges                                0          .   Number of purge operations executed
MAIN.n_obj_purged                            0          .   Number of purged objects
MAIN.n_gzip                                  0         0.00 Gzip operations
MAIN.n_gunzip                          2285498         6.40 Gunzip operations

**Comment by rabbitt** [comment]
Unfortunately, this is just a mirror of http://varnishsnmp.sourceforge.net - you'll want to reach out to the project there with questions. 

Sorry :-/
